sudo: required
services:
        - docker
before_install:
        - docker build -t swet1805/first-docker -f Dockerfile.dev .

script: 
        - docker run -e CI=true swet1805/first-docker npm run test 
