sudo: required
services:
        - docker
before_install:
        - docker build -t swet1805/first-docker -f Dockerfile.dev .

script: 
        - docker run -e CI=true swet1805/first-docker npm run test

deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-us-east-2-801104768954"       
        bucket_path: "docker-react"
        on:
           branch: master     
        access_key_id: 
                secure: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "$AWS_SECRET_KEY"
           

